#!/bin/sh

# Usage:
# $ script/release # Setting github.token in .gitconfig is required
# $ GITHUB_TOKEN=... script/release

set -e
latest_tag=$(git describe --abbrev=0 --tags)
goxz -d dist/$latest_tag -z -os darwin -arch amd64,386
goxz -d dist/$latest_tag -z -os linux -arch amd64,386,arm64
ghr -u mackerelio -r mackerel-plugin-json $latest_tag dist/$latest_tag
