name: goreleaser

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  goreleaser:
    uses: mackerelio/workflows/.github/workflows/goreleaser.yml@7286c9384065633bf7d1ff6e733138deca03a764 # v1.10.0

